# Generated by Django 2.1.2 on 2019-03-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_logging_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logging',
            name='manager',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
    ]
