# Generated by Django 2.1.2 on 2019-02-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190204_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='month_a4',
            new_name='month_A4',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='today_a4',
            new_name='today_A4',
        ),
    ]
