# Generated by Django 2.1.2 on 2019-02-09 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190209_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytable',
            name='eighth_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='table_eighth_time', to='login.Student'),
        ),
        migrations.AlterField(
            model_name='studytable',
            name='fifth_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='table_fifth_time', to='login.Student'),
        ),
        migrations.AlterField(
            model_name='studytable',
            name='fourth_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='table_fourth_time', to='login.Student'),
        ),
        migrations.AlterField(
            model_name='studytable',
            name='second_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='table_second_time', to='login.Student'),
        ),
        migrations.AlterField(
            model_name='studytable',
            name='seventh_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='table_seventh_time', to='login.Student'),
        ),
        migrations.AlterField(
            model_name='studytable',
            name='sixth_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='table_sixth_time', to='login.Student'),
        ),
        migrations.AlterField(
            model_name='studytable',
            name='third_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='table_third_time', to='login.Student'),
        ),
    ]
