# Generated by Django 2.1.2 on 2019-03-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_unbrella_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unbrella',
            name='is_borrowed',
        ),
        migrations.AddField(
            model_name='battery',
            name='status',
            field=models.CharField(choices=[('대여가능', '대여가능'), ('대여중', '대여중'), ('대여불가', '대여불가')], default='대여가능', max_length=4),
        ),
        migrations.AddField(
            model_name='studytable',
            name='status',
            field=models.CharField(choices=[('대여가능', '대여가능'), ('대여중', '대여중'), ('대여불가', '대여불가')], default='대여가능', max_length=4),
        ),
    ]
