# Generated by Django 2.1.5 on 2019-02-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190207_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='table_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studytable',
            name='start_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
