# Generated by Django 2.1.5 on 2019-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190309_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timea', models.DateTimeField(auto_now_add=True)),
                ('timeb', models.DateTimeField(auto_now_add=True)),
                ('diff', models.FloatField()),
            ],
        ),
    ]
