# Generated by Django 2.1.5 on 2019-03-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_studytable_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studytable',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='time_table',
            name='week_day',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
