# Generated by Django 2.1.2 on 2019-02-04 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190204_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='umbrella',
        ),
        migrations.AddField(
            model_name='unbrella',
            name='borrowed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.UserInfo'),
        ),
    ]
