# Generated by Django 2.1.2 on 2019-03-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190306_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='is_borrowed',
        ),
        migrations.RemoveField(
            model_name='lan',
            name='is_borrowed',
        ),
        migrations.RemoveField(
            model_name='studytable',
            name='status',
        ),
        migrations.AddField(
            model_name='lan',
            name='status',
            field=models.CharField(choices=[('대여가능', '대여가능'), ('대여중', '대여중'), ('대여불가', '대여불가')], default='대여가능', max_length=4),
        ),
    ]
