# Generated by Django 2.1.5 on 2019-04-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190324_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unbrella',
            name='return_time',
        ),
        migrations.AddField(
            model_name='unbrella',
            name='ex_lender',
            field=models.CharField(blank=True, default='', max_length=9, null=True),
        ),
    ]
