# Generated by Django 2.1.2 on 2019-02-04 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190204_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unbrella',
            name='borrowed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unbrella', to='login.UserInfo'),
        ),
    ]
