# Generated by Django 2.1.2 on 2019-02-09 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190209_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='borrowed_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lan',
        ),
        migrations.AlterField(
            model_name='lan',
            name='borrowed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lan_borrowed_by', to='login.Student'),
        ),
        migrations.DeleteModel(
            name='Battery',
        ),
    ]
