# Generated by Django 2.1.5 on 2019-04-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190420_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='ex_lender',
            field=models.CharField(blank=True, default='', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='cable',
            name='ex_lender',
            field=models.CharField(blank=True, default='', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='lan',
            name='ex_lender',
            field=models.CharField(blank=True, default='', max_length=9, null=True),
        ),
    ]
