# Generated by Django 2.1.2 on 2019-02-04 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190204_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('borrowed', models.BooleanField(default=False)),
                ('borrowed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='login.UserInfo')),
            ],
        ),
        migrations.AlterField(
            model_name='unbrella',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
