# Generated by Django 2.1.2 on 2019-02-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190205_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytable',
            name='StartTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
