# Generated by Django 2.1.2 on 2020-03-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190420_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('borrowed_time', models.DateTimeField(auto_now_add=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('reservation_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('대여가능', '대여가능'), ('대여중', '대여중'), ('대여불가', '대여불가'), ('대여신청중', '대여신청중')], default='대여가능', max_length=5)),
                ('ex_lender', models.CharField(blank=True, default='', max_length=9, null=True)),
            ],
        ),
    ]
