# Generated by Django 2.1.2 on 2019-03-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190310_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('is_borrowed', models.BooleanField(default=False)),
                ('borrowed_time', models.DateTimeField(auto_now_add=True)),
                ('cable_type', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='is_attend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cable',
            name='borrowed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.Student'),
        ),
    ]
