# Generated by Django 2.1.2 on 2019-03-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190315_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_attend',
            field=models.BooleanField(default=True),
        ),
    ]
