# Generated by Django 2.1.2 on 2019-02-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20190209_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='borrowed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.Student'),
        ),
        migrations.AlterField(
            model_name='lan',
            name='borrowed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.Student'),
        ),
    ]
