# Generated by Django 2.1.2 on 2019-03-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20190315_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='unbrella',
            name='status',
            field=models.CharField(choices=[('대여가능', '대여가능'), ('대여중', '대여중'), ('대여불가', '대여불가'), ('대여신청중', '대여신청중')], default='대여가능', max_length=5),
        ),
    ]
