# Generated by Django 2.1.5 on 2019-02-10 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20190209_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studytable',
            name='eighth_time',
        ),
        migrations.RemoveField(
            model_name='studytable',
            name='fifth_time',
        ),
        migrations.RemoveField(
            model_name='studytable',
            name='first_time',
        ),
        migrations.RemoveField(
            model_name='studytable',
            name='fourth_time',
        ),
        migrations.RemoveField(
            model_name='studytable',
            name='second_time',
        ),
        migrations.RemoveField(
            model_name='studytable',
            name='seventh_time',
        ),
        migrations.RemoveField(
            model_name='studytable',
            name='sixth_time',
        ),
        migrations.RemoveField(
            model_name='studytable',
            name='third_time',
        ),
        migrations.AddField(
            model_name='studytable',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studytable',
            name='lender',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.Student'),
        ),
        migrations.AddField(
            model_name='studytable',
            name='start_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
