# Generated by Django 2.1.2 on 2019-03-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_unbrella_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='status',
            field=models.CharField(choices=[('대여가능', '대여가능'), ('대여중', '대여중'), ('대여불가', '대여불가'), ('대여신청중', '대여신청중')], default='대여가능', max_length=5),
        ),
        migrations.AddField(
            model_name='lan',
            name='status',
            field=models.CharField(choices=[('대여가능', '대여가능'), ('대여중', '대여중'), ('대여불가', '대여불가'), ('대여신청중', '대여신청중')], default='대여가능', max_length=5),
        ),
    ]
