# Generated by Django 2.1.2 on 2020-03-15 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200315_1249'),
    ]

    operations = [
        migrations.RenameModel('Lan', 'OldLan'),
        migrations.CreateModel(
            name="NewLan",
            fields=[
                ('rentalitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True,serialize=False, to='login.RentalItem')),
                ('borrowed_by', models.OneToOneField('login.Student', related_name='la', null=True, blank=True, on_delete=models.DO_NOTHING)),
                ('return_time', models.DateTimeField(auto_now_add=True)),                
            ],
            bases=('login.RentalItem',),
        ),
        migrations.DeleteModel('OldLan'),
        migrations.RenameModel('NewLan', 'Lan')
    ]
