# Generated by Django 2.1.5 on 2019-03-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20190316_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1000)),
                ('updated_text', models.TextField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=10)),
                ('userid', models.CharField(max_length=8)),
            ],
        ),
    ]
