# Generated by Django 2.1.2 on 2020-03-15 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20200315_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalitem',
            name='number',
        ),
        migrations.AddField(
            model_name='battery',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lan',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unbrella',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battery',
            name='rentalitem_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='login.RentalItem'),
        ),
        migrations.AlterField(
            model_name='lan',
            name='rentalitem_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='login.RentalItem'),
        ),
        migrations.AlterField(
            model_name='unbrella',
            name='rentalitem_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='login.RentalItem'),
        ),
    ]
