# Generated by Django 2.1.2 on 2020-03-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200315_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='cable_type',
            field=models.CharField(choices=[('C타입', 'C타입'), ('5핀', '5핀'), ('8핀', '8핀')], default='5핀', max_length=10),
        ),
    ]
