# Generated by Django 2.1.2 on 2020-03-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_cable_cable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cable',
            name='rentalitem_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='login.RentalItem'),
        ),
    ]
