# Generated by Django 2.1.5 on 2019-03-18 07:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20190317_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unbrella',
            name='borrowed_time',
        ),
        migrations.AddField(
            model_name='cable',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cable',
            name='reservation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cable',
            name='status',
            field=models.CharField(choices=[('대여가능', '대여가능'), ('대여중', '대여중'), ('대여불가', '대여불가'), ('대여신청중', '대여신청중')], default='대여가능', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='A4_count',
            field=models.PositiveIntegerField(default=0, error_messages={'max_value': '하루 대여량은 50장을 넘길 수 없습니다.'}, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='cable',
            name='cable_type',
            field=models.CharField(choices=[('C타입 케이블', 'C타입 케이블'), ('5핀 케이블', '5핀 케이블'), ('8핀 케이블', '8핀 케이블')], default='5핀 케이블', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='month_A4',
            field=models.PositiveIntegerField(default=0, error_messages={'max_value': '한달 대여량은 500장을 넘길 수 없습니다.'}, validators=[django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='today_A4',
            field=models.PositiveIntegerField(default=0, error_messages={'max_value': '하루 대여량은 50장을 넘길 수 없습니다.'}, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='unbrella',
            name='borrowed_by',
            field=models.OneToOneField(blank=True, error_messages={'unique': '한 사람 당 한 개씩만 대여 가능합니다.'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='un', to='login.Student'),
        ),
    ]
