# Generated by Django 2.1.2 on 2020-03-28 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20200315_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hdmi',
            fields=[
                ('rentalitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='login.RentalItem')),
                ('return_time', models.DateTimeField(auto_now_add=True)),
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('borrowed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hdmi', to='login.Student')),
            ],
            bases=('login.rentalitem',),
        ),
    ]
