# Generated by Django 2.1.2 on 2019-03-19 04:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20190318_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='unbrella',
            name='id',
        ),
        migrations.AddField(
            model_name='unbrella',
            name='borrowed_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battery',
            name='number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cable',
            name='number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lan',
            name='number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='unbrella',
            name='borrowed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='un', to='login.Student'),
        ),
        migrations.AlterField(
            model_name='unbrella',
            name='number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
