# Generated by Django 2.1.2 on 2020-03-28 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_hdmi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unbrella',
            options={'ordering': ['number']},
        ),
    ]
