# Generated by Django 2.1.2 on 2019-03-17 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20190317_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cable',
            name='reservation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cable',
            name='status',
            field=models.CharField(choices=[('대여가능', '대여가능'), ('대여중', '대여중'), ('대여불가', '대여불가'), ('대여신청중', '대여신청중')], default='대여가능', max_length=5),
        ),
        migrations.AlterField(
            model_name='cable',
            name='cable_type',
            field=models.CharField(choices=[('C타입 케이블', 'C타입 케이블'), ('5핀 케이블', '5핀 케이블'), ('8핀 케이블', '8핀 케이블')], default='5핀 케이블', max_length=10),
        ),
    ]
