# Generated by Django 2.1.2 on 2019-03-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190319_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lan',
            name='borrowed_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
