# Generated by Django 2.1.5 on 2019-03-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_timetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='unbrella',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
