# Generated by Django 2.1.5 on 2019-03-10 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190310_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='lan',
            name='borrowed_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lan',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
