# Generated by Django 2.1.5 on 2019-03-16 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_complain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unbrella',
            name='borrowed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='un', to='login.Student'),
        ),
    ]
