# Generated by Django 2.1.2 on 2019-03-17 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20190317_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='A4_count',
            field=models.PositiveIntegerField(default=0, error_messages={'max_value': '하루 대여량은 50장을 넘길 수 없습니다.'}, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='month_A4',
            field=models.PositiveIntegerField(default=0, error_messages={'max_value': '한달 대여량은 500장을 넘길 수 없습니다.'}, validators=[django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='today_A4',
            field=models.PositiveIntegerField(default=0, error_messages={'max_value': '하루 대여량은 50장을 넘길 수 없습니다.'}, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
