# Generated by Django 2.1.2 on 2019-03-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20190317_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unbrella',
            name='borrowed_by',
            field=models.OneToOneField(blank=True, error_messages={'unique': '한 사람 당 한 개씩만 대여 가능합니다.'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='un', to='login.Student'),
        ),
    ]
