# Generated by Django 2.1.2 on 2019-03-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20190317_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unbrella',
            name='id',
        ),
        migrations.AlterField(
            model_name='unbrella',
            name='number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
