# Generated by Django 2.1.2 on 2019-03-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20190319_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lan',
            name='id',
        ),
        migrations.AlterField(
            model_name='battery',
            name='number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cable',
            name='number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lan',
            name='number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
