# Generated by Django 2.1.2 on 2019-03-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20190319_1347'),
        ('login', '0018_auto_20190319_1253'),
    ]

    operations = [
    ]
