# Generated by Django 2.1.2 on 2019-01-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('stdID', models.CharField(max_length=8)),
                ('HB', models.BooleanField(default=False)),
            ],
        ),
    ]
